## Variables
@name = google
@domain = gmail.com
@userId = 2

### 회사 등록
POST http://localhost:8080/admin/company
accessToken: {{accessToken}}
Content-Type: application/json

{
  "name": "{{name}}",
  "domain": "{{domain}}"
}

### 회원 권한 수정
PUT http://localhost:8080/admin/role/{{userId}}
accessToken: {{accessToken}}