### 이메일 인증 코드 전송
POST http://localhost:8080/email
Content-Type: application/json

{
  "email": "{{email}}"
}

### 인증 코드 확인
POST http://localhost:8080/email/verify
Content-Type: application/json

{
  "email": "{{email}}",
  "authCode": "qzhKdxPQ"
}