## Variables
@title = 제목테스트
@content = 내용테스트
@update_title = 제목수정테스트
@update_content = 내용수정테스트


### 게시물 작성
POST http://localhost:8080/feed
accessToken: {{accessToken}}
Content-Type: application/json

{
  "title" : "{{title}}",
  "content" : "{{content}}"
}

### 게시물 조회
GET http://localhost:8080/feed?page=0&size=5
accessToken: {{accessToken}}
Content-Type: application/json

### 게시물 수정
PUT http://localhost:8080/feed/1
accessToken: {{accessToken}}
Content-Type: application/json

{
  "title" : "{{update_title}}",
  "content" : "{{update_content}}"
}

### 게시물 삭제
DELETE http://localhost:8080/feed/1
accessToken: {{accessToken}}
Content-Type: application/json

### 소속별 게시물 조회
GET http://localhost:8080/feed?page=0&size=5
accessToken: {{accessToken}}
Content-Type: application/json

### 팔로잉 회원 게시물 조회
GET http://localhost:8080/feed/following
accessToken: {{accessToken}}

