## Variables
@userId = 1

### 팔로우 추가
POST http://localhost:8080/users/follow/{{userId}}
accessToken: {{accessToken}}

### 팔로우 취소
DELETE http://localhost:8080/users/follow/{{userId}}
accessToken: {{accessToken}}

### 팔로잉 목록 조회
GET http://localhost:8080/users/{{userId}}/following
accessToken: {{accessToken}}

### 팔로워 목록 조회
GET http://localhost:8080/users/{{userId}}/follower
accessToken: {{accessToken}}