### 유저 회원 가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "username":"{{username}}",
  "nickname":"{{nickname}}",
  "password":"{{password}}",
  "email":"{{email}}",
  "intro": "{{intro}}"
}

### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}"
}

> {%
  client.log(response.headers.valueOf("accessToken"));
  client.log(response.headers.valueOf("refreshToken"));
  client.global.set("accessToken", response.headers.valueOf("accessToken"));
  client.global.set("refreshToken", response.headers.valueOf("refreshToken"));
%}

### 회원 프로필 수정
PUT http://localhost:8080/users
accessToken: {{accessToken}}
Content-Type: application/json

{
  "intro":"update intro",
  "nickname":"updateName",
  "isTalTye": false
}

### 비밀번호 변경
PATCH http://localhost:8080/users
accessToken: {{accessToken}}
Content-Type: application/json

{
  "currentPassword":"{{password}}",
  "newPassword":"1qaz2wsx3edc!@#"
}

### 리프레시 토큰 테스트
POST http://localhost:8080/users/reissue
refresh-token:{{Refresh-Token}}

> {%
  client.global.set("Access-Token", response.headers.valueOf("Authorization"));
  client.global.set("Refresh-Token", response.headers.valueOf("refresh-token"));
%}

### 이메일 인증 코드 전송
POST http://localhost:8080/email
Content-Type: application/json

{
  "email": "{{email}}"
}

### 인증 코드 확인
POST http://localhost:8080/email/verify
Content-Type: application/json

{
  "email": "{{email}}",
  "authCode": "l3h4C3xR"
}